name: Build and Push to Google Artifact Registry

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  # 🔴 [REQUIRED CHANGE] เปลี่ยนตัวแปร 4 ตัวด้านล่างให้ตรงกับ Google Cloud ของคุณ
  PROJECT_ID: fisheries-idp-4091     # Project ID บน Google Cloud
  GAR_LOCATION: asia-southeast3      # Region ของ Artifact Registry
  REPOSITORY: my-repo                # ชื่อ Repository ใน Artifact Registry
  IMAGE: my-docker-app               # ชื่อ Docker Image ที่ต้องการ

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          # 🟡 [OPTIONAL CHANGE] แก้เป็นเวอร์ชัน Node.js ที่โปรเจกต์คุณใช้
          node-version: "22"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Generate Prisma Client
        # 🟡 [OPTIONAL CHANGE] ถ้าโปรเจกต์ไม่ได้ใช้ Prisma ให้ลบ 2 บรรทัดนี้ทิ้งได้เลย
        run: npx prisma generate

      - name: Run Lint
        run: npm run lint

      - name: Run Build
        run: npm run build
        env:
          DATABASE_URL: "postgresql://dummy:dummy@localhost:5432/dummy"

  build-and-push:
    name: Build and Push Docker Image
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v3
        with:
          # 🔴 [REQUIRED CHANGE] คุณต้องนำไฟล์ JSON Key จาก Service Account ของ GCP
          # มาสร้างเป็น Secret ในหน้าเว็บ GitHub ของโปรเจกต์ใหม่ โดยตั้งชื่อว่า GCP_CREDENTIALS
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v3

      - name: Docker Auth
        run: |-
          gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev

      - name: Build Docker Image
        run: |-
          docker build -t ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ github.sha }} .
          docker tag ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ github.sha }} ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:latest

      - name: Push Docker Image
        run: |-
          docker push ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ github.sha }}
          docker push ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:latest
